spring.application.name=spring-clickhouse-db
spring.datasource.url=jdbc:clickhouse:http://localhost:8123/default
spring.datasource.driverClassName=com.clickhouse.jdbc.ClickHouseDriver
spring.datasource.username=x
spring.datasource.password=x
